# Generated by Django 2.1.4 on 2018-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backups_settings_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_template', models.CharField(max_length=100, verbose_name='Имя шаблона')),
                ('lead_time', models.TimeField(verbose_name='время начала копирования')),
                ('completion_time', models.TimeField(verbose_name='Время завершения копирования')),
                ('command_backups', models.CharField(max_length=1500, verbose_name='команда для копирования')),
                ('report_formation', models.BooleanField(verbose_name='создание отчета - tru false')),
                ('email_report', models.EmailField(max_length=254, verbose_name='email адрес')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания шаблона')),
                ('date_upgrade', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Настройки резервного копирования',
                'db_table': 'backups_settigs_template',
            },
        ),
        migrations.CreateModel(
            name='bacups_hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('ip', models.GenericIPAddressField(verbose_name='ip адрес')),
                ('dir', models.CharField(max_length=1500, verbose_name='Путь к катологу')),
                ('mount', models.CharField(max_length=1500, verbose_name='монтирование каталога')),
                ('umount', models.CharField(max_length=1500, verbose_name='размонтирование каталога')),
                ('mount_time', models.TimeField(verbose_name='время монтирования каталога')),
                ('umount_time', models.TimeField(verbose_name='время размонтирования каталога')),
                ('date_create', models.DateTimeField(verbose_name='дата создания записи')),
            ],
        ),
        migrations.CreateModel(
            name='client_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Клиент',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='storge_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'хранилище',
                'db_table': 'storage',
            },
        ),
    ]
