# Generated by Django 2.1.4 on 2018-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bacups_hosts',
        ),
        migrations.AddField(
            model_name='client_backup',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания записи'),
        ),
        migrations.AddField(
            model_name='client_backup',
            name='dir',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Путь к катологу'),
        ),
        migrations.AddField(
            model_name='client_backup',
            name='ip',
            field=models.GenericIPAddressField(null=True, protocol='IPv4', verbose_name='ip адрес'),
        ),
        migrations.AddField(
            model_name='client_backup',
            name='mount',
            field=models.CharField(blank=True, max_length=1500, verbose_name='монтирование каталога'),
        ),
        migrations.AddField(
            model_name='client_backup',
            name='mount_time',
            field=models.TimeField(auto_now=True, verbose_name='время монтирования каталога'),
        ),
        migrations.AddField(
            model_name='client_backup',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='client_backup',
            name='umount',
            field=models.CharField(blank=True, max_length=1500, verbose_name='размонтирование каталога'),
        ),
        migrations.AddField(
            model_name='client_backup',
            name='umount_time',
            field=models.TimeField(auto_now=True, verbose_name='время размонтирования каталога'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания записи'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='dir',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Путь к катологу'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='ip',
            field=models.GenericIPAddressField(null=True, protocol='IPv4', verbose_name='ip адрес'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='mount',
            field=models.CharField(blank=True, max_length=1500, verbose_name='монтирование каталога'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='mount_time',
            field=models.TimeField(auto_now=True, verbose_name='время монтирования каталога'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='umount',
            field=models.CharField(blank=True, max_length=1500, verbose_name='размонтирование каталога'),
        ),
        migrations.AddField(
            model_name='storge_backup',
            name='umount_time',
            field=models.TimeField(auto_now=True, verbose_name='время размонтирования каталога'),
        ),
        migrations.AlterModelTable(
            name='client_backup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='storge_backup',
            table=None,
        ),
    ]
